### PR TITLE
option for minimum 2 empty desktops on startup

### PR DESCRIPTION
**Pull request by soumyaDghosh**
This PR implements a feature to have atleast 2 empty when the user logs in.

This is how it looks

image

### CODE REVIEW

**Comment by Ubiquitine** [comment]
How does this option work with "Keep one spare empty desktop" ?
Wouldn't it be better to have an option to select the number of spare desktops, so the user can select how many spare desktops to keep.

**Comment by soumyaDghosh** [comment]
> How does this option work with "Keep one spare empty desktop" ?
> Wouldn't it be better to have an option to select the number of spare desktops, so the user can select how many spare desktops to keep.

Well, this worked, until I borked the code myself and mistakenly force pushed. Now, I am not able to reproduce it. But my plan is to not count the current focused desktop as an empty one. 

EDIT: Basically my target is to reproduce how gnome handles it. Initially, there are 2 desktops, and Desktop 1 will be there even if currentDesktop is Desktop 2. Until, I open a window in Desktop 2, Desktop 1 will be there, may it be empty or not.

**Comment by Ubiquitine** [comment]
But might be confused, but "Keep one spare empty desktop" option does exactly the same thing. When enabled the first desktop, even if it empty does not count and you have another "Desktop 2" as a spare one. Once you move to "Desktop 2" and open a window there, new spare "Desktop 3" is created. 
In fact the option of "Keep one spare empty desktop" was inspired by Gnome behavior.

**Comment by soumyaDghosh** [comment]
> But might be confused, but "Keep one spare empty desktop" option does exactly the same thing. When enabled the first desktop, even if it empty does not count and you have another "Desktop 2" as a spare one. Once you move to "Desktop 2" and open a window there, new spare "Desktop 3" is created. 
> In fact the option of "Keep one spare empty desktop" was inspired by Gnome behavior. 

Nope it doesn't do that, atleast initially. As much I understand from the code, `oneSpare` logic, initially when you just logged in, only keeps 1 desktop, where as it should keep 2, and it count take only desktop 1 as empty if it's currentDesktop and the length of desktops is less than 2. I think this should be the logic.

**Comment by Ubiquitine** [comment]
I think I get what you try to chive here. 

Here's some explanation on what it looks like with and without  "Keep one spare empty desktop" option is checked:
**Unchecked**:
Screenshot 2024-12-10 171805
**Checked**:
Screenshot 2024-12-10 171715

Now, `currentDesktop` is the desktop that you are seeing in this moment. When you just logged in, `currentDesktop` will always be The first desktop. 
This is what happens if you open/move window on the spare "Desktop 2":
Screenshot 2024-12-10 173001

If the "Desktop 1" is **empty** though, and you open a ne window on the "Desktop 2", this is what's going to happen:
1. "Desktop 1" would be deleted
2. "Desktop 2" would be renamed to "Desktop 1"
3. A new spare "Desktop 2" is created. 

**So**, from your changes I assume that you want to keep "Desktop 1" even if it's empty, so it won't get deleted during the `balanceDesktops` operation. 
This is a valid option to consider. The only thing that confuses me is the naming for variable and options. Because this option **doesn't guarantee** that at least 2 desktop will be spared (especially if `oneSpare` is disabled). 
I think if you rename the option to something like `preserveFirstDesktop` and give it a description like "_Always keep the first desktop_", that would make much more sense.

**Comment by soumyaDghosh** [comment]
I got up with this patch... Which is working, I think

```diff
--- a/contents/code/main.js
+++ b/contents/code/main.js
@@ -1,10 +1,9 @@
 var busy = false;
 var oneSpare = readConfig("oneSpare", false);
 var backHome = readConfig("backHome", false);
-var keepAtLeastTwoDesktops = readConfig("keepAtLeastTwoDesktops", false);
 
 function isDesktopEmpty(desktop) {
-    if (keepAtLeastTwoDesktops && workspace.desktops[0] == desktop) {
+    if (workspace.desktops[0] == desktop && isDesktopEmpty(workspace.desktops[1])) {
         return false;
     }
     for (var i in workspace.windowList()) {
@@ -15,7 +14,6 @@ function isDesktopEmpty(desktop) {
     }
     return true;
 }
-
 /**
  * Closing focused desktops is allowed only if backHome is enabled
  */
@@ -58,7 +56,7 @@ function balanceDesktops() {
     busy = true;
 
     if (oneSpare) {
-        for (var i = keepAtLeastTwoDesktops ? 1 : 0 ; i < workspace.desktops.length - 1 ; i++ ) {
+        for (var i = 0 ; i < workspace.desktops.length - 1 ; i++ ) {
             if (isDesktopEmpty(workspace.desktops[i]) && mayCloseDesktop(workspace.desktops[i])){
                 deleteDesktop(workspace.desktops[i]);
             }
```

**Comment by soumyaDghosh** [comment]
image

This is a screenshot!

**Comment by Ubiquitine** [comment]
This patch makes sense now. 
Also, There is no need to check `isDesktopEmpty(workspace.desktops[1])` , just this check 
`if (workspace.desktops[0] == desktop && isDesktopEmpty(workspace.desktops[1]))` 
is enough to skip the first desktop.
Another approach is to change the starting index in `balanceDesktops()` function, e.g. 
`for (var i = 1 ; i < workspace.desktops.length .....`
Would you please submit it in a new MR or update this MR. I guess there is no need for user UI option as well.
I agree that always keeping the first desktop regardless if it's empty is a good idea and mimics the Gnomes behavior better.

**Comment by Ubiquitine** [comment]
Actually I have some free time, so let me quickly implement it as an option, just in case someone doesn't like it.

**Comment by Ubiquitine** [comment]
Added this option to v0.4.0

**Pull request closed without merging**
